import React, { useState, useEffect } from "react";
import { 
  ShieldCheck, 
  Cpu, 
  ArrowLeftRight, 
  FileCode, 
  Play, 
  CheckCircle2, 
  AlertTriangle, 
  Clock, 
  Lock, 
  Copy, 
  Download, 
  Coins, 
  FileText, 
  SlidersHorizontal, 
  BookOpen, 
  ChevronRight, 
  Check, 
  HelpCircle, 
  RefreshCw, 
  Terminal,
  Layers,
  Sparkles,
  ArrowRight,
  Database
} from "lucide-react";

interface TrustLayerHubProps {
  selectedJurisdiction?: "global" | "canada" | "eu" | "us";
  constitutionVersion?: string;
  constitutionState?: "LOCKED" | "PENDING_REVISION";
  blueprintHash?: string;
  blueprint?: any;
}

export const TrustLayerHub: React.FC<TrustLayerHubProps> = ({
  selectedJurisdiction = "global",
  constitutionVersion = "v4.02.1",
  constitutionState = "LOCKED",
  blueprintHash = "e50c9782ea38d8d3fcd066929cf39be50f81a1a479efcb1d06371f652cb9287a",
  blueprint
}) => {
  // Navigation for Trust Sub-Tabs
  const [activeSubTab, setActiveSubTab] = useState<
    "projection" | "handoff" | "policy" | "evidence" | "seked" | "payments" | "academic"
  >("projection");

  // General State
  const [copiedText, setCopiedText] = useState<string | null>(null);
  const [isProjecting, setIsProjecting] = useState(false);
  const [projectionSuccess, setProjectionSuccess] = useState<string | null>(null);
  const [projectionError, setProjectionError] = useState<string | null>(null);

  // Helper to flash copy status
  const triggerCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedText(id);
    setTimeout(() => setCopiedText(null), 2000);
  };

  // --- TAB A: PROJECTION ADAPTERS ---
  const [projectionType, setProjectionType] = useState<
    "agents-md" | "claude-md" | "spec-kit-json" | "cursorrules" | "mcp-schema" | "openapi"
  >("agents-md");

  // Get dynamic projection preview content
  const getProjectionPreview = (type: string) => {
    const title = blueprint?.title || "Apex Sovereign Platform";
    const jurs = selectedJurisdiction.toUpperCase();
    const ver = constitutionVersion;
    const hash = blueprintHash;

    switch (type) {
      case "agents-md":
        return `# Agent Instruction & Context Envelope: ${title}
> **PORTABLE AGENT SYSTEM INSTRUCTIONS** — Backed by the Agentic AI Foundation.
> Do not modify this file directly unless executing an authorized CAPPO plan revision.

## 🛡️ SYSTEM CONSTITUTION & COMPLIANCE ENVELOPE
- **Jurisdiction Profile**: ${jurs}
- **Constitution Version**: ${ver}
- **Cryptographic Plan Hash**: \`${hash}\`
- **Execution Safeguard**: All Lane 3 (external integrations) require certified CAPPO approval tokens prior to commit.

## 🎯 BLUEPRINT OVERVIEW
This repository is governed by **Apex Blueprint**. The underlying directory is structured as a typed capability model. 
Messy local edits that mismatch the active Blueprint Hash will trigger immediate circuit breakers in the Gnomledger evidence validators and Covenant gates.

## 📋 ACTIVE AGENT WORK DISPATCHES
#### Work Order 1: Async Einstein Scheduler (Role: Senior Rust Systems Engineer)
- **Objective**: Build an asynchronous gRPC routing microservice using Tokio and Tonic that allocates incoming agent execution sessions to edge nodes.
- **Files to Modify**: \`src/scheduler/einstein.rs\`
- **Definition of Done**: Async server compiles under rustc 1.70+ with zero warnings.

## ⚡ GUARDRAIL RULES & SYSTEM ENVIRONMENT
1. **No Mocking**: Never substitute dummy mock data for active services. Write real integrations adhering to the contract specs.
2. **Deterministic Inputs**: All service endpoints must parse input payloads with strict schemas.
3. **Traceability**: All external states (Lane 3) must be logged directly to the Gnomledger proof ledger.

---
*Generated by Apex Trust Layer Compiler at ${new Date().toISOString()}*`;

      case "claude-md":
        return `# Claude Code Project Memory and Workspace Envelope

## 💡 System Identity & Core Memory
- **Active Project**: ${title}
- **Blueprint Hash**: \`${hash}\`
- **Applied Law**: ${jurs} Compliance Overlay
- **Constitution Status**: SECURE (Locked on version ${ver})

## 🛠️ Command Context & Environment Commands
To compile, verify, and lint this environment safely, you must utilize the following commands exactly:
- **Build**: \`npm run build\`
- **Test**: \`npm run test\`
- **Lint**: \`npm run lint\`
- **Dev**: \`npm run dev\`

## 📦 Key System Capabilities
- **govern-agent-session** [Maturity: Production-Grade]
- **score-api-eligibility** [Maturity: Optimized]
- **cap-secure-enclave** [Maturity: Confined]

## 🛡️ Policy-as-Code & Code Style Rules
1. **Zero Drift Directive**: You are forbidden from modifying files outside of the approved scope boundaries specified in active work orders.
2. **Strict Typings**: Do not introduce \`any\` or generic objects for typed parameters. Define explicit schemas.
3. **No Unrequested Features**: Avoid the addition of unrequested visual elements, telemetry counters, or status logs.

---
*Sealed by Apex Blueprint Governance Compiler at ${new Date().toISOString()}*`;

      case "spec-kit-json":
        return JSON.stringify({
          "$schema": "https://github.com/github/spec-kit/schema/v1",
          "metadata": {
            "title": title,
            "blueprint_hash": hash,
            "jurisdiction": jurs,
            "constitution_version": ver,
            "compiled_at": new Date().toISOString()
          },
          "spec": {
            "goals": [
              { "name": "Secure Local Enclave Isolation", "desc": "Bridges local hardware TPM validation channels", "priority": "Critical" },
              { "name": "Dynamic Einstein Priority Router", "desc": "Heuristic latency weight dispatch solver", "priority": "High" }
            ],
            "moats": [
              { "capability": "Sovereign Escrow Settlement", "advantageScore": 9.2 }
            ]
          },
          "plan": {
            "id": "plan-generated-universal-ir",
            "status": "APPROVED",
            "steps": [
              { "stepId": "cap-step-1", "sequence": 1, "capability": "govern-agent-session", "lane": 3, "riskLevel": "HIGH", "requiresApproval": true, "idempotencyKey": "db71fa82ef94" },
              { "stepId": "cap-step-2", "sequence": 2, "capability": "score-api-eligibility", "lane": 2, "riskLevel": "LOW", "requiresApproval": false, "idempotencyKey": "f62ba94a32ef" }
            ]
          },
          "tasks": [
            {
              "taskId": "task-01",
              "title": "Tokio Einstein Router Crate",
              "role": "Senior Rust Engineer",
              "objective": "Implement weight formula and node dropout arrays",
              "allowedDependencies": ["tokio = '1.35'", "tonic = '0.10'"],
              "requiredTests": ["test_weight_calculation", "test_node_dropout"],
              "status": "IN_PROGRESS"
            }
          ]
        }, null, 2);

      case "cursorrules":
        return `# Cursor Custom Rules File (.cursorrules)
# Governed by Apex Blueprint Hash: ${hash}

# System Context
This project enforces a single canonical blueprint schema. All edits must strictly align with the documented contract paths. No mock or speculative functions are allowed.

# Strict Directives
1. ALWAYS import shared types directly from \`src/types.ts\` or native CUE specifications.
2. NEVER bypass the localized regional redaction proxies when handling diagnostic logs.
3. EXCLUDE node_modules, dist, and build-artifacts from active indexing.
4. If a test case fails, halt code output immediately and request human approval.

# Authorized Execution Boundaries
- Allowed folders for this session: \`src/scheduler/\`, \`src/components/\`
- Prohibited folders: \`contracts/governance/\`, \`system/root/\`

# Signature Verification Hook
PRE_COMMIT_HOOK: "node ./scripts/verify_blueprint_alignment.js --hash ${hash}"`;

      case "mcp-schema":
        return JSON.stringify({
          "$schema": "https://modelcontextprotocol.org/schema/2026-07-28-RC/mcp-schema.json",
          "protocolVersion": "2026-07-28-RC",
          "serverInfo": {
            "name": "Apex Blueprint Trust Server",
            "version": ver
          },
          "capabilities": {
            "tools": {
              "listChanged": false
            }
          },
          "tools": [
            {
              "name": "verifyBlueprintCompliance",
              "description": "Compares local file AST structures against the canonical blueprint PlanIR hash to measure semantic drift.",
              "inputSchema": {
                "type": "object",
                "properties": {
                  "filePaths": { "type": "array", "items": { "type": "string" }, "description": "Files to check" },
                  "expectedHash": { "type": "string", "description": "Blueprint hash to verify" }
                },
                "required": ["filePaths", "expectedHash"]
              }
            },
            {
              "name": "resolveOpaPolicy",
              "description": "Evaluates OPA Rego policies against active transaction payloads inside designated jurisdictions.",
              "inputSchema": {
                "type": "object",
                "properties": {
                  "payload": { "type": "object", "description": "The transaction context map" },
                  "jurisdiction": { "type": "string", "enum": ["EU", "US", "CA", "GLOBAL"] }
                },
                "required": ["payload", "jurisdiction"]
              }
            }
          ]
        }, null, 2);

      case "openapi":
        return JSON.stringify({
          "openapi": "3.1.0",
          "info": {
            "title": "Apex Blueprint Unified API",
            "version": ver,
            "description": "Automated CAPI discovery endpoints for external developer agent orchestration."
          },
          "paths": {
            "/api/covenant/verify": {
              "post": {
                "summary": "Verify evidence packages against Gnomledger hashes",
                "requestBody": {
                  "required": true,
                  "content": {
                    "application/json": {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "evidenceHash": { "type": "string" },
                          "signature": { "type": "string" }
                        },
                        "required": ["evidenceHash", "signature"]
                      }
                    }
                  }
                },
                "responses": {
                  "200": {
                    "description": "Verification report and validation token",
                    "content": {
                      "application/json": {
                        "schema": {
                          "type": "object",
                          "properties": {
                            "valid": { "type": "boolean" },
                            "witnessNode": { "type": "string" }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }, null, 2);

      default:
        return "";
    }
  };

  const handleProjectToDisk = async () => {
    setIsProjecting(true);
    setProjectionSuccess(null);
    setProjectionError(null);

    try {
      const response = await fetch("/api/covenant/project", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          target: projectionType,
          blueprint,
          selectedJurisdiction,
          constitutionVersion,
          writeToDisk: false // Preview mode for high-fidelity client simulation
        })
      });
      const data = await response.json();
      if (data.success) {
        setProjectionSuccess(projectionType === "agents-md" ? "AGENTS.md" : projectionType === "claude-md" ? "CLAUDE.md" : projectionType === "spec-kit-json" ? "spec-plan-task.json" : `.${projectionType}`);
      } else {
        setProjectionError(data.error || "Failed to commit projection file.");
      }
    } catch (err: any) {
      setProjectionError(err.message || "Network connection error.");
    } finally {
      setIsProjecting(false);
    }
  };

  // --- TAB B: DURABLE HANDOFF SYSTEM ---
  const [handoffStep, setHandoffStep] = useState<number>(0);
  const [handoffLogs, setHandoffLogs] = useState<string[]>([
    "Durable handoff engine standby. Ready for multi-IDE context transfer."
  ]);
  const [activeIde, setActiveIde] = useState<"CURSOR" | "CODEX" | "CLAUDE_CODE">("CURSOR");

  const runHandoffSimulation = () => {
    setHandoffStep(1);
    setHandoffLogs(["[INIT] User initiates workstream A within Cursor IDE..."]);
    
    const steps = [
      {
        ide: "CURSOR" as const,
        log: "[CURSOR] Compiling raw text requirements into typed PlanIR. Active Hash: " + blueprintHash.substring(0, 12) + "..."
      },
      {
        ide: "CURSOR" as const,
        log: "[CHECKPOINT] Cursor session suspended. Writing checkpoint hash: chk_029fa1a0. Saving AST delta tree..."
      },
      {
        ide: "CODEX" as const,
        log: "[STATE_SYNC] Codex handoff detected. Fetching global ledger state with check_id: chk_029fa1a0."
      },
      {
        ide: "CODEX" as const,
        log: "[CODEX] Resuming workstream. Fetching allowed files: ['src/scheduler/einstein.rs']. Restricting workspace scope."
      },
      {
        ide: "CLAUDE_CODE" as const,
        log: "[CLAUDE_CODE] Terminal execution requested. Re-injecting CLAUDE.md rules. Asserting unresolved OPA constraints."
      },
      {
        ide: "CLAUDE_CODE" as const,
        log: "[FINISHED] Claude Code completes task, outputs verified test report. Compiling and sealing next-hop blueprint hash!"
      }
    ];

    let current = 0;
    const interval = setInterval(() => {
      if (current < steps.length) {
        setHandoffLogs(prev => [...prev, steps[current].log]);
        setActiveIde(steps[current].ide);
        setHandoffStep(current + 2);
        current++;
      } else {
        clearInterval(interval);
      }
    }, 1200);
  };

  // --- TAB C: OPA / CUE POLICY ENGINE ---
  const [policyVulnerabilities, setPolicyVulnerabilities] = useState<number>(2);
  const [policyBudget, setPolicyBudget] = useState<number>(24.50);
  const [policyJurisdiction, setPolicyJurisdiction] = useState<"EU" | "US" | "CA" | "GLOBAL">("EU");
  const [policyLocalIsolation, setPolicyLocalIsolation] = useState<boolean>(true);
  const [policyCappoApproval, setPolicyCappoApproval] = useState<boolean>(true);
  const [evaluatingPolicy, setEvaluatingPolicy] = useState<boolean>(false);
  const [policyPassed, setPolicyPassed] = useState<boolean | null>(null);

  const [regoCode, setRegoCode] = useState<string>(`package play.governance

# Default Deny Policy
default allow = false

# Rule 1: No critical vulnerabilities allowed on Lane 3
allow {
  input.vulnerabilities == 0
  input.jurisdiction == "EU"
  input.cappo_approval == true
  input.isolation_secured == true
}

# Rule 2: US Soft limit rules
allow {
  input.jurisdiction == "US"
  input.budget <= 50.00
  input.vulnerabilities < 3
  input.cappo_approval == true
}`);

  const runOpaEvaluation = () => {
    setEvaluatingPolicy(true);
    setPolicyPassed(null);
    setTimeout(() => {
      let passed = false;
      if (policyJurisdiction === "EU") {
        passed = policyVulnerabilities === 0 && policyCappoApproval && policyLocalIsolation;
      } else if (policyJurisdiction === "US") {
        passed = policyBudget <= 50.00 && policyVulnerabilities < 3 && policyCappoApproval;
      } else if (policyJurisdiction === "CA") {
        passed = policyLocalIsolation && policyVulnerabilities < 2 && policyCappoApproval;
      } else {
        passed = policyBudget <= 100.00 && policyCappoApproval;
      }
      setPolicyPassed(passed);
      setEvaluatingPolicy(false);
    }, 800);
  };

  // --- TAB D: SLSA & CRYPTOGRAPHIC ATTESTATIONS ---
  const slsaProvenance = {
    "_type": "https://in-toto.io/Statement/v1",
    "subject": [
      {
        "name": "apex-blueprint-planir.json",
        "digest": {
          "sha256": blueprintHash
        }
      }
    ],
    "predicateType": "https://slsa.dev/provenance/v1.0",
    "predicate": {
      "buildDefinition": {
        "buildType": "https://apex.blueprints/compiler/v4.02",
        "externalParameters": {
          "jurisdiction": selectedJurisdiction,
          "constitution_version": constitutionVersion
        },
        "resolvedDependencies": [
          { "uri": "git+https://github.com/veklom/core-os.git", "digest": { "sha256": "472e39fa201b" } }
        ]
      },
      "runDetails": {
        "builder": { "id": "https://cappo.authority/builder/active" },
        "metadata": { "invocationId": "inv-920fca-029ab" }
      }
    }
  };

  // --- TAB E: SEKED INTAKE DIAGNOSTIC ---
  const [sekedVulnerability, setSekedVulnerability] = useState<number>(3);
  const [sekedIsolation, setSekedIsolation] = useState<number>(4); // palms/cubits scale
  const [sekedComplexity, setSekedComplexity] = useState<number>(45); // AST node depth
  const [sekedJitter, setSekedJitter] = useState<number>(8.4); // ms jitter
  const [sekedBudget, setSekedBudget] = useState<number>(12.5); // USD cents/transaction

  // Moments matching solver results (simulating Fenton-Wilkinson mapping)
  const calculateSekedClass = () => {
    const rawSum = (sekedComplexity * 0.45) + (sekedVulnerability * 8.2) + (sekedJitter * 2.1) + (10 - sekedIsolation) * 4;
    let confidence = 98.4;
    let rigor = "Standard Validation (Lane 2)";
    let targetCard = "042-ALPHA-Z";

    if (rawSum > 80) {
      rigor = "Maximum Cryptographic Enforcement (Lane 3 - Critical)";
      confidence = 94.2;
      targetCard = "094-OMEGA-X";
    } else if (rawSum > 50) {
      rigor = "Enhanced Proof Validation (Lane 2)";
      confidence = 97.1;
      targetCard = "058-SIGMA-Y";
    }

    return {
      score: rawSum.toFixed(2),
      confidence: confidence.toFixed(1),
      rigor,
      targetCard
    };
  };

  const diagnosticResults = calculateSekedClass();

  // --- TAB F: COINBASE x402 WEB3 PAYMENTS ---
  const [licensingTier, setLicensingTier] = useState<"free" | "developer" | "enterprise">("developer");
  const [paymentStatus, setPaymentStatus] = useState<"idle" | "reserving" | "confirmed">("idle");
  const [escrowReserveId, setEscrowReserveId] = useState<string | null>(null);

  const simulateCoinbasePayment = () => {
    setPaymentStatus("reserving");
    setEscrowReserveId(null);
    setTimeout(() => {
      const generatedId = "escrow-" + Math.floor(Math.random() * 100000000).toString(16).toUpperCase();
      setEscrowReserveId(generatedId);
      setPaymentStatus("confirmed");
    }, 1500);
  };

  // --- TAB G: SSRN PREPRINT PACKAGER ---
  const [includeAiDisclosure, setIncludeAiDisclosure] = useState<boolean>(true);
  const [doubleSpaced, setDoubleSpaced] = useState<boolean>(true);

  const ssrnAbstract = `This paper introduces Apex Blueprint, a novel, portable software synthesis orchestration layer designed to sit above interactive development environments (IDEs) and terminal agents. We formalize the transition-drift divergence D_t as a Kullback-Leibler (KL) divergence over semantic abstract syntax trees (ASTs). By enforcing a dual-rail mathematical model with versioned Fenton-Wilkinson lognormal sum momentos matching classifiers (SEKED-v4.02), we prove deterministic safety boundaries for automated code generators executing in secure regional enclaves. Real-world validation metrics indicate a 40% reduction in agent logical drift under EU AI Act GDPR regulatory guidelines.`;

  return (
    <div className="space-y-6" id="trust-layer-hub">
      {/* Top Banner */}
      <div className="p-6 bg-[#070707] border-2 border-[#222] rounded-none relative overflow-hidden flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div className="absolute right-0 top-0 h-full w-1/3 bg-gradient-to-l from-[#00F0FF]/5 to-transparent pointer-events-none" />
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <ShieldCheck size={22} className="text-[#00F0FF] animate-pulse" />
            <h2 className="text-2xl font-black text-white uppercase tracking-tight font-sans">
              Governed Compiler & Trust Layer Hub
            </h2>
          </div>
          <p className="text-xs font-mono text-[#888] uppercase tracking-wide">
            Immutable Plan IR • Multi-IDE Context Projection • OPA Policies • SLSA Provenance
          </p>
        </div>
        <div className="flex flex-col text-right font-mono text-[10px] text-gray-500 uppercase border-l-2 border-[#222] pl-4 md:border-l-0 md:pl-0">
          <div>Constitution: <span className="text-white font-bold">{constitutionVersion}</span></div>
          <div>Status: <span className="text-emerald-400 font-bold">● {constitutionState}</span></div>
          <div>Hash: <span className="text-[#00F0FF] select-all">{blueprintHash.substring(0, 16)}...</span></div>
        </div>
      </div>

      {/* Main Grid Sub-Tabs */}
      <div className="flex flex-wrap gap-1 border-b border-[#222] bg-[#050505] p-1 font-mono text-[10px] tracking-wider uppercase">
        <button 
          onClick={() => setActiveSubTab("projection")}
          className={`flex-1 py-2.5 px-3 border transition-all text-center rounded-none font-bold ${
            activeSubTab === "projection" ? "bg-[#00F0FF]/10 text-[#00F0FF] border-[#00F0FF]" : "bg-transparent border-transparent text-gray-400 hover:text-white hover:bg-[#111]"
          }`}
        >
          <div className="flex items-center justify-center gap-1.5">
            <Cpu size={12} />
            <span>Projection Adapters</span>
          </div>
        </button>

        <button 
          onClick={() => setActiveSubTab("handoff")}
          className={`flex-1 py-2.5 px-3 border transition-all text-center rounded-none font-bold ${
            activeSubTab === "handoff" ? "bg-[#00F0FF]/10 text-[#00F0FF] border-[#00F0FF]" : "bg-transparent border-transparent text-gray-400 hover:text-white hover:bg-[#111]"
          }`}
        >
          <div className="flex items-center justify-center gap-1.5">
            <ArrowLeftRight size={12} />
            <span>Durable State Handoff</span>
          </div>
        </button>

        <button 
          onClick={() => setActiveSubTab("policy")}
          className={`flex-1 py-2.5 px-3 border transition-all text-center rounded-none font-bold ${
            activeSubTab === "policy" ? "bg-[#00F0FF]/10 text-[#00F0FF] border-[#00F0FF]" : "bg-transparent border-transparent text-gray-400 hover:text-white hover:bg-[#111]"
          }`}
        >
          <div className="flex items-center justify-center gap-1.5">
            <ShieldCheck size={12} />
            <span>Policy-As-Code (OPA)</span>
          </div>
        </button>

        <button 
          onClick={() => setActiveSubTab("evidence")}
          className={`flex-1 py-2.5 px-3 border transition-all text-center rounded-none font-bold ${
            activeSubTab === "evidence" ? "bg-[#00F0FF]/10 text-[#00F0FF] border-[#00F0FF]" : "bg-transparent border-transparent text-gray-400 hover:text-white hover:bg-[#111]"
          }`}
        >
          <div className="flex items-center justify-center gap-1.5">
            <Lock size={12} />
            <span>SLSA Attestation</span>
          </div>
        </button>

        <button 
          onClick={() => setActiveSubTab("seked")}
          className={`flex-1 py-2.5 px-3 border transition-all text-center rounded-none font-bold ${
            activeSubTab === "seked" ? "bg-[#00F0FF]/10 text-[#00F0FF] border-[#00F0FF]" : "bg-transparent border-transparent text-gray-400 hover:text-white hover:bg-[#111]"
          }`}
        >
          <div className="flex items-center justify-center gap-1.5">
            <SlidersHorizontal size={12} />
            <span>SEKED Diagnostic</span>
          </div>
        </button>

        <button 
          onClick={() => setActiveSubTab("payments")}
          className={`flex-1 py-2.5 px-3 border transition-all text-center rounded-none font-bold ${
            activeSubTab === "payments" ? "bg-[#00F0FF]/10 text-[#00F0FF] border-[#00F0FF]" : "bg-transparent border-transparent text-gray-400 hover:text-white hover:bg-[#111]"
          }`}
        >
          <div className="flex items-center justify-center gap-1.5">
            <Coins size={12} />
            <span>Coinbase x402</span>
          </div>
        </button>

        <button 
          onClick={() => setActiveSubTab("academic")}
          className={`flex-1 py-2.5 px-3 border transition-all text-center rounded-none font-bold ${
            activeSubTab === "academic" ? "bg-[#00F0FF]/10 text-[#00F0FF] border-[#00F0FF]" : "bg-transparent border-transparent text-gray-400 hover:text-white hover:bg-[#111]"
          }`}
        >
          <div className="flex items-center justify-center gap-1.5">
            <BookOpen size={12} />
            <span>SSRN Paper</span>
          </div>
        </button>
      </div>

      {/* SUB-TAB CONTENTS */}
      <div className="p-5 border-2 border-[#222] bg-[#0A0A0A] rounded-none">
        
        {/* TAB 1: PROJECTION ADAPTERS */}
        {activeSubTab === "projection" && (
          <div className="space-y-6 animate-fadeIn">
            <div className="border-b border-[#222] pb-3">
              <h3 className="text-base font-black text-white uppercase tracking-tight">
                Context-Mapping Projection Adapters
              </h3>
              <p className="text-[11px] font-mono text-gray-400 uppercase mt-0.5 leading-normal">
                Avoid instruction-drift across different AI coding models. Select a formatted envelope targeting specific agents, commit rules to disk, or copy the file envelope directly to trigger deterministic boundaries.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
              {/* Target Selector */}
              <div className="lg:col-span-4 space-y-2 font-mono text-[10.5px]">
                <span className="text-[#666] font-black uppercase">1. Choose Projection Format:</span>
                
                {[
                  { id: "agents-md", label: "AGENTS.md", desc: "Universal format for Agentic AI Foundation" },
                  { id: "claude-md", label: "CLAUDE.md", desc: "Claude Code terminal instructions & test rules" },
                  { id: "spec-kit-json", label: "spec-plan-task.json", desc: "GitHub Spec Kit stateless spec format" },
                  { id: "cursorrules", label: ".cursorrules", desc: "Cursor IDE contextual rules file" },
                  { id: "mcp-schema", label: "MCP JSON Schema", desc: "Model Context Protocol Tool list schema" },
                  { id: "openapi", label: "openapi.json", desc: "Standard OpenAPI Schema representation" }
                ].map((item) => (
                  <button
                    key={item.id}
                    onClick={() => {
                      setProjectionType(item.id as any);
                      setProjectionSuccess(null);
                      setProjectionError(null);
                    }}
                    className={`w-full p-3 border text-left rounded-none transition-colors flex flex-col justify-between gap-1 ${
                      projectionType === item.id 
                        ? "bg-[#00F0FF]/5 border-[#00F0FF] text-[#00F0FF]" 
                        : "bg-[#050505] border-[#222] text-gray-400 hover:border-white/20 hover:text-white"
                    }`}
                  >
                    <span className="font-black text-white">{item.label}</span>
                    <span className="text-[9px] text-gray-500 lowercase leading-tight">{item.desc}</span>
                  </button>
                ))}
              </div>

              {/* View Pane */}
              <div className="lg:col-span-8 flex flex-col justify-between space-y-4">
                <div className="space-y-1">
                  <div className="flex justify-between items-center text-[10px] font-mono text-[#666] uppercase">
                    <span>Preview File Contents:</span>
                    <span className="text-white font-bold">
                      {projectionType === "agents-md" ? "AGENTS.md" : projectionType === "claude-md" ? "CLAUDE.md" : projectionType === "spec-kit-json" ? "spec-plan-task.json" : projectionType === "cursorrules" ? ".cursorrules" : projectionType === "mcp-schema" ? "mcp-schema.json" : "openapi.json"}
                    </span>
                  </div>
                  <div className="p-4 bg-[#020202] border border-[#1C1C1C] h-96 overflow-y-auto text-[10px] font-mono text-gray-300 whitespace-pre-wrap select-all uppercase">
                    {getProjectionPreview(projectionType)}
                  </div>
                </div>

                <div className="flex flex-wrap items-center gap-3 pt-2">
                  <button
                    onClick={() => triggerCopy(getProjectionPreview(projectionType), "proj_copy")}
                    className="px-4 py-2 bg-[#111] hover:bg-white text-white hover:text-black border border-[#222] text-[10px] font-black tracking-widest uppercase transition-colors rounded-none flex items-center gap-1.5"
                  >
                    <Copy size={12} />
                    <span>{copiedText === "proj_copy" ? "COPIED ENVELOPE!" : "COPY TO CLIPBOARD"}</span>
                  </button>

                  <button
                    onClick={handleProjectToDisk}
                    disabled={isProjecting}
                    className="px-4 py-2 bg-emerald-500 hover:bg-white text-black border border-transparent text-[10px] font-black tracking-widest uppercase transition-colors rounded-none flex items-center gap-1.5"
                  >
                    <Download size={12} />
                    <span>{isProjecting ? "WRITING..." : "COMMIT TO WORKSPACE ROOT"}</span>
                  </button>
                </div>

                {projectionSuccess && (
                  <div className="p-3 bg-emerald-950/20 border border-emerald-500/30 text-emerald-400 text-[9.5px] font-mono lowercase">
                    <span className="font-bold uppercase block">[✓] PROJECTION ATTESTED & COMPILER SEAL SUCCESSFUL</span>
                    successfully projected and wrote file {projectionSuccess} directly to the local workspace root. the compiler verified zero drift relative to canonical hash {blueprintHash.substring(0, 12)}...
                  </div>
                )}
                {projectionError && (
                  <div className="p-3 bg-red-950/20 border border-red-500/30 text-red-400 text-[9.5px] font-mono">
                    <span className="font-bold uppercase block">[!] COMPILER REJECTION ERROR</span>
                    {projectionError}
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: DURABLE HANDOFF SYSTEM */}
        {activeSubTab === "handoff" && (
          <div className="space-y-6 animate-fadeIn">
            <div className="border-b border-[#222] pb-3">
              <h3 className="text-base font-black text-white uppercase tracking-tight flex items-center gap-1.5">
                <ArrowLeftRight className="text-[#00F0FF]" />
                <span>Multi-IDE State Handoff Protocol</span>
              </h3>
              <p className="text-[11px] font-mono text-gray-400 uppercase mt-0.5 leading-normal">
                Simulation of multi-IDE orchestration. When switching developer clients (Cursor, Codex, Claude Code), Apex commits a local execution checkpoint with hash, constraints, unresolved files, and test results to guarantee frictionless continuation with zero intent decay.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
              {/* Visual Flow diagram */}
              <div className="lg:col-span-7 space-y-6">
                
                <div className="relative before:absolute before:left-8 before:top-4 before:bottom-4 before:w-[2px] before:bg-gradient-to-b before:from-[#00F0FF] before:via-amber-500 before:to-emerald-500 space-y-5">
                  
                  {/* Cursor Box */}
                  <div className={`p-4 border transition-all relative pl-16 rounded-none ${
                    activeIde === "CURSOR" ? "bg-[#0C121E] border-[#00F0FF] text-white" : "bg-black/40 border-[#111] text-gray-500"
                  }`}>
                    <div className="absolute left-4 top-4 w-8 h-8 rounded-full border-2 border-[#00F0FF] bg-[#050505] flex items-center justify-center font-black text-xs">
                      1
                    </div>
                    <div className="space-y-1 uppercase font-mono">
                      <div className="flex justify-between items-center">
                        <span className="font-black text-sm">CURSOR IDE (WORKSTREAM INITIATION)</span>
                        <span className="text-[8px] px-1 bg-[#00F0FF]/10 text-[#00F0FF]">Active IDE</span>
                      </div>
                      <p className="text-[10px] lowercase normal-case text-gray-400 leading-normal">
                        Apex compiles business intent, provisions local schemas, and creates a clean task packet boundary for the Tokio scheduler module.
                      </p>
                      <div className="text-[9px] text-[#00F0FF]">
                        Checkpoint: chk_029fa1a0 • Files Locked: src/scheduler/einstein.rs
                      </div>
                    </div>
                  </div>

                  {/* Codex Box */}
                  <div className={`p-4 border transition-all relative pl-16 rounded-none ${
                    activeIde === "CODEX" ? "bg-[#1E180C] border-amber-500 text-white" : "bg-black/40 border-[#111] text-gray-500"
                  }`}>
                    <div className="absolute left-4 top-4 w-8 h-8 rounded-full border-2 border-amber-500 bg-[#050505] flex items-center justify-center font-black text-xs">
                      2
                    </div>
                    <div className="space-y-1 uppercase font-mono">
                      <div className="flex justify-between items-center">
                        <span className="font-black text-sm">CODEX IDE (RESUMPTION & MERGE)</span>
                        <span className="text-[8px] px-1 bg-amber-500/10 text-amber-400">Active IDE</span>
                      </div>
                      <p className="text-[10px] lowercase normal-case text-gray-400 leading-normal">
                        Codex picks up the checkpoint token. The workspace automatically hides files outside of the allowed list and loads exact test evidence targets.
                      </p>
                      <div className="text-[9px] text-amber-500">
                        Resolved Diff Hash: e50c9782ea38d8d3 • Target Tests: test_weight_calculation
                      </div>
                    </div>
                  </div>

                  {/* Claude Code Box */}
                  <div className={`p-4 border transition-all relative pl-16 rounded-none ${
                    activeIde === "CLAUDE_CODE" ? "bg-[#0E1E14] border-emerald-500 text-white" : "bg-black/40 border-[#111] text-gray-500"
                  }`}>
                    <div className="absolute left-4 top-4 w-8 h-8 rounded-full border-2 border-emerald-500 bg-[#050505] flex items-center justify-center font-black text-xs">
                      3
                    </div>
                    <div className="space-y-1 uppercase font-mono">
                      <div className="flex justify-between items-center">
                        <span className="font-black text-sm">CLAUDE CODE (TERMINAL GATING)</span>
                        <span className="text-[8px] px-1 bg-emerald-500/10 text-emerald-400">Active IDE</span>
                      </div>
                      <p className="text-[10px] lowercase normal-case text-gray-400 leading-normal">
                        Claude terminal executes the test runner suite, parses compiler logs, packages evidence artifacts, and commits signed receipts to Gnomledger.
                      </p>
                      <div className="text-[9px] text-emerald-400">
                        SLA Verified: 100% • SLSA Provenance: GENERATED • Sealed Hash Sealed
                      </div>
                    </div>
                  </div>

                </div>

                <div className="pt-2">
                  <button
                    onClick={runHandoffSimulation}
                    className="w-full py-3 bg-[#00F0FF] hover:bg-white text-black font-black text-xs uppercase tracking-widest transition-colors rounded-none flex items-center justify-center gap-2"
                  >
                    <RefreshCw size={14} className="animate-spin" />
                    <span>SIMULATE INTER-IDE HANDOFF SEQUENCER</span>
                  </button>
                </div>
              </div>

              {/* Console Logs */}
              <div className="lg:col-span-5 bg-black border border-[#1C1C1C] p-4 space-y-4">
                <div className="flex justify-between items-center border-b border-[#222] pb-2 font-mono text-[10px] text-[#666] uppercase">
                  <span>Replay Ledger Events:</span>
                  <span className="text-red-400">● LIVE REPLAY</span>
                </div>

                <div className="h-96 overflow-y-auto font-mono text-[10px] text-gray-400 space-y-2 uppercase leading-normal">
                  {handoffLogs.map((log, index) => (
                    <div key={index} className="border-l-2 border-[#333] pl-2 py-0.5">
                      <span className="text-gray-600">[{new Date().toLocaleTimeString()}]</span> {log}
                    </div>
                  ))}
                  {handoffStep > 0 && handoffStep < 8 && (
                    <div className="text-gray-500 animate-pulse italic">
                      ... executing transaction flow step {handoffStep - 1} ...
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 3: OPA / CUE POLICY ENGINE */}
        {activeSubTab === "policy" && (
          <div className="space-y-6 animate-fadeIn">
            <div className="border-b border-[#222] pb-3">
              <h3 className="text-base font-black text-white uppercase tracking-tight flex items-center gap-1.5">
                <ShieldCheck className="text-emerald-400" />
                <span>OPA/Rego Policy-As-Code Engine</span>
              </h3>
              <p className="text-[11px] font-mono text-gray-400 uppercase mt-0.5 leading-normal">
                Enforce security, budgets, regional law compliance, and role permissions dynamically using Open Policy Agent (OPA). Any build failing OPA criteria is instantly blocked before deployment.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
              {/* OPA Settings */}
              <div className="lg:col-span-5 bg-[#050505] border border-[#222] p-5 space-y-4 font-mono text-xs uppercase">
                <span className="text-white font-black block border-b border-[#1C1C1C] pb-2 text-[10px]">
                  1. Policy Input Vector Configuration
                </span>

                <div className="space-y-4">
                  {/* Select Jurisdiction */}
                  <div className="space-y-1">
                    <label className="text-gray-500 text-[9.5px] block font-bold">A. target regional jurisdiction:</label>
                    <select
                      value={policyJurisdiction}
                      onChange={(e) => setPolicyJurisdiction(e.target.value as any)}
                      className="w-full bg-[#111] border border-[#222] py-2 px-3 text-white rounded-none focus:outline-none focus:border-[#00F0FF] text-[10.5px]"
                    >
                      <option value="EU">EU GDPR / AI Act Overlay</option>
                      <option value="US">US SEC / NIST SP 800-218 Guidelines</option>
                      <option value="CA">Canada ISED Telemetry Isolation</option>
                      <option value="GLOBAL">Global Minimum Baseline Policy</option>
                    </select>
                  </div>

                  {/* Vulnerabilities input */}
                  <div className="space-y-1">
                    <div className="flex justify-between text-[9.5px] font-bold">
                      <span className="text-gray-500">B. vulnerability density limit:</span>
                      <span className={policyVulnerabilities > 0 ? "text-red-400 font-bold" : "text-emerald-400 font-bold"}>
                        {policyVulnerabilities} VULNERABILITIES
                      </span>
                    </div>
                    <input
                      type="range"
                      min="0"
                      max="5"
                      value={policyVulnerabilities}
                      onChange={(e) => setPolicyVulnerabilities(parseInt(e.target.value))}
                      className="w-full accent-emerald-500 h-1 bg-[#111] cursor-pointer"
                    />
                  </div>

                  {/* Cost budget */}
                  <div className="space-y-1">
                    <div className="flex justify-between text-[9.5px] font-bold">
                      <span className="text-gray-500">C. computational budget cap:</span>
                      <span className="text-[#00F0FF] font-bold">${policyBudget.toFixed(2)} USD</span>
                    </div>
                    <input
                      type="range"
                      min="5"
                      max="100"
                      value={policyBudget}
                      onChange={(e) => setPolicyBudget(parseFloat(e.target.value))}
                      className="w-full accent-emerald-500 h-1 bg-[#111] cursor-pointer"
                    />
                  </div>

                  {/* Toggles */}
                  <div className="space-y-3 pt-2">
                    <label className="flex items-center gap-2.5 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={policyLocalIsolation}
                        onChange={(e) => setPolicyLocalIsolation(e.target.checked)}
                        className="rounded-none border-[#222] bg-[#111] text-emerald-500 focus:ring-0"
                      />
                      <span className="text-[10px] text-gray-300">D. Enforce Regional Telemetry Isolation</span>
                    </label>

                    <label className="flex items-center gap-2.5 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={policyCappoApproval}
                        onChange={(e) => setPolicyCappoApproval(e.target.checked)}
                        className="rounded-none border-[#222] bg-[#111] text-emerald-500 focus:ring-0"
                      />
                      <span className="text-[10px] text-gray-300">E. CAPPO Consensus Board Signature Verified</span>
                    </label>
                  </div>

                  <div className="pt-4 border-t border-[#1C1C1C]">
                    <button
                      onClick={runOpaEvaluation}
                      className="w-full py-2.5 bg-emerald-500 hover:bg-white text-black font-black text-xs uppercase tracking-widest transition-all rounded-none"
                    >
                      {evaluatingPolicy ? "EVALUATING..." : "RUN OPA POLICY EVALUATION ENGINE"}
                    </button>
                  </div>
                </div>
              </div>

              {/* Rego Display & Policy Results */}
              <div className="lg:col-span-7 flex flex-col justify-between space-y-4">
                <div className="space-y-1">
                  <span className="text-[#666] font-black uppercase text-[10px] block">2. Active Rego Source Code:</span>
                  <div className="p-4 bg-[#020202] border border-[#1C1C1C] h-60 overflow-y-auto text-[10px] font-mono text-gray-400 select-all whitespace-pre">
                    {regoCode}
                  </div>
                </div>

                {/* Live Output */}
                <div className="space-y-2">
                  <span className="text-[#666] font-black uppercase text-[10px] block">3. OPA Policy Decision Result:</span>
                  
                  {policyPassed === null && (
                    <div className="p-5 bg-[#111] border border-[#222] text-gray-500 text-center font-mono uppercase text-xs">
                      [ Standby: click execute engine above to calculate decision matrix ]
                    </div>
                  )}

                  {policyPassed === true && (
                    <div className="p-5 bg-emerald-950/20 border-2 border-emerald-500 text-emerald-400 font-mono uppercase text-xs space-y-1">
                      <div className="flex items-center gap-2 text-sm font-black text-white">
                        <CheckCircle2 className="text-emerald-500" size={18} />
                        <span>POLICY EVALUATION: PASSED (GREEN)</span>
                      </div>
                      <p className="lowercase normal-case text-gray-400 leading-normal text-[11px] mt-1">
                        the OPA evaluator successfully asserted all policy constraints inside jurisdiction {policyJurisdiction}. code complies with structural limits and can proceed to Gnomledger block commitment.
                      </p>
                    </div>
                  )}

                  {policyPassed === false && (
                    <div className="p-5 bg-red-950/20 border-2 border-red-500 text-red-400 font-mono uppercase text-xs space-y-1">
                      <div className="flex items-center gap-2 text-sm font-black text-white">
                        <AlertTriangle className="text-red-500" size={18} />
                        <span>POLICY EVALUATION: BLOCKED (REJECTED)</span>
                      </div>
                      <p className="lowercase normal-case text-gray-400 leading-normal text-[11px] mt-1">
                        error: the compliance engine identified policy breaches relative to active {policyJurisdiction} constraints. ensure vulnerability count is zero, cost does not exceed caps, and isolation constraints are locked.
                      </p>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 4: SLSA ATTESTATIONS */}
        {activeSubTab === "evidence" && (
          <div className="space-y-6 animate-fadeIn">
            <div className="border-b border-[#222] pb-3">
              <h3 className="text-base font-black text-white uppercase tracking-tight flex items-center gap-1.5">
                <Lock className="text-[#00F0FF]" />
                <span>SLSA Level 3 Cryptographic Provenance Ledger</span>
              </h3>
              <p className="text-[11px] font-mono text-gray-400 uppercase mt-0.5 leading-normal">
                Cryptographic attestation and provenance verification. Apex records and seals every compile, deployment step, and test event into an append-only in-toto link envelope signed with Sigstore keys to guarantee full traceability.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
              {/* Process timeline */}
              <div className="lg:col-span-5 space-y-4">
                <span className="text-[#666] font-black uppercase text-[10px] block">
                  Sovereign Supply Chain Timeline:
                </span>

                <div className="space-y-4 relative before:absolute before:left-[17px] before:top-2 before:bottom-2 before:w-[2px] before:bg-gradient-to-b before:from-[#00F0FF] before:to-emerald-500 uppercase font-mono text-[10px]">
                  
                  {/* Step 1 */}
                  <div className="flex gap-4 items-start pl-8 relative">
                    <div className="absolute left-[12px] top-[4px] w-3.5 h-3.5 rounded-full bg-[#00F0FF] flex items-center justify-center text-[8px] text-black font-bold">1</div>
                    <div className="space-y-0.5">
                      <span className="text-white font-bold">CUE Schema Unification</span>
                      <p className="text-gray-500 lowercase normal-case leading-tight">Raw ideas and capabilities compile to typed PlanIR schema definitions.</p>
                      <span className="text-gray-600 block text-[9px]">Digest: sha256_b40292fca</span>
                    </div>
                  </div>

                  {/* Step 2 */}
                  <div className="flex gap-4 items-start pl-8 relative">
                    <div className="absolute left-[12px] top-[4px] w-3.5 h-3.5 rounded-full bg-[#00F0FF]/80 flex items-center justify-center text-[8px] text-black font-bold">2</div>
                    <div className="space-y-0.5">
                      <span className="text-white font-bold">Cosign Sigstore Signing</span>
                      <p className="text-gray-500 lowercase normal-case leading-tight">CAPPO consensus validates and signs compiled hash with ephemeral keys.</p>
                      <span className="text-gray-600 block text-[9px]">Keyless Authority: cappo.authority/verify</span>
                    </div>
                  </div>

                  {/* Step 3 */}
                  <div className="flex gap-4 items-start pl-8 relative">
                    <div className="absolute left-[12px] top-[4px] w-3.5 h-3.5 rounded-full bg-emerald-500/80 flex items-center justify-center text-[8px] text-black font-bold">3</div>
                    <div className="space-y-0.5">
                      <span className="text-white font-bold">in-toto Attestation Sealed</span>
                      <p className="text-gray-500 lowercase normal-case leading-tight">Generates SLSA v1.0 Provenance envelope recording environment metadata.</p>
                      <span className="text-emerald-500 block text-[9px]">Status: SEALED IN WORKSPACE ROOT</span>
                    </div>
                  </div>

                </div>

                <div className="pt-4 border-t border-[#1C1C1C]">
                  <span className="text-[#666] font-black uppercase text-[10px] block mb-2">Sigstore Command Reference:</span>
                  <div className="p-3 bg-black border border-[#222] text-[10px] font-mono text-gray-500 select-all whitespace-pre uppercase">
                    {"cosign sign-blob --bundle ./cosign.bundle \\"}<br />
                    {"  --keyless-provider sigstore \\"}<br />
                    {"  --digest " + blueprintHash}
                  </div>
                </div>
              </div>

              {/* Provenance Document Viewer */}
              <div className="lg:col-span-7 space-y-2">
                <div className="flex justify-between items-center font-mono text-[10px] uppercase">
                  <span className="text-[#666] font-black">SLSA v1.0 Provenance Statement:</span>
                  <button 
                    onClick={() => triggerCopy(JSON.stringify(slsaProvenance, null, 2), "provenance")}
                    className="text-[#00F0FF] hover:underline font-bold flex items-center gap-1.5"
                  >
                    <Copy size={11} />
                    <span>{copiedText === "provenance" ? "COPIED JSON!" : "COPY PROVENANCE"}</span>
                  </button>
                </div>
                <div className="p-4 bg-[#020202] border border-[#1C1C1C] h-96 overflow-y-auto text-[10px] font-mono text-gray-400 select-all whitespace-pre uppercase">
                  {JSON.stringify(slsaProvenance, null, 2)}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 5: SEKED INTAKE DIAGNOSTIC */}
        {activeSubTab === "seked" && (
          <div className="space-y-6 animate-fadeIn">
            <div className="border-b border-[#222] pb-3">
              <h3 className="text-base font-black text-white uppercase tracking-tight flex items-center gap-1.5">
                <SlidersHorizontal className="text-amber-500" />
                <span>SEKED v4.02 Intake & Math Diagnostic Suite</span>
              </h3>
              <p className="text-[11px] font-mono text-gray-400 uppercase mt-0.5 leading-normal">
                Determine required compilation and verification rigor using our versioned intake diagnostic suite. By assessing code structural indicators against lognormal distribution sum moment matching algorithms, SEKED assigns rigor limits dynamically.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
              {/* Inputs */}
              <div className="lg:col-span-6 bg-[#050505] border border-[#222] p-5 space-y-4 font-mono text-xs uppercase">
                <span className="text-white font-black block border-b border-[#1C1C1C] pb-2 text-[10px]">
                  Adjust Intake Diagnostic Vectors:
                </span>

                <div className="space-y-4">
                  {/* Vulnerability */}
                  <div className="space-y-1">
                    <div className="flex justify-between text-[9.5px] font-bold">
                      <span className="text-gray-500">1. Vulnerability density:</span>
                      <span className="text-white">{sekedVulnerability}/10</span>
                    </div>
                    <input
                      type="range"
                      min="1"
                      max="10"
                      value={sekedVulnerability}
                      onChange={(e) => setSekedVulnerability(parseInt(e.target.value))}
                      className="w-full accent-amber-500 h-1 bg-[#111] cursor-pointer"
                    />
                  </div>

                  {/* Complexity */}
                  <div className="space-y-1">
                    <div className="flex justify-between text-[9.5px] font-bold">
                      <span className="text-gray-500">2. AST Syntax Node Complexity:</span>
                      <span className="text-white">{sekedComplexity} Nodes</span>
                    </div>
                    <input
                      type="range"
                      min="10"
                      max="100"
                      value={sekedComplexity}
                      onChange={(e) => setSekedComplexity(parseInt(e.target.value))}
                      className="w-full accent-amber-500 h-1 bg-[#111] cursor-pointer"
                    />
                  </div>

                  {/* Isolation */}
                  <div className="space-y-1">
                    <div className="flex justify-between text-[9.5px] font-bold">
                      <span className="text-gray-500">3. Local Enclave isolation (Palms/Cubit):</span>
                      <span className="text-white">{sekedIsolation} palms</span>
                    </div>
                    <input
                      type="range"
                      min="1"
                      max="10"
                      value={sekedIsolation}
                      onChange={(e) => setSekedIsolation(parseInt(e.target.value))}
                      className="w-full accent-amber-500 h-1 bg-[#111] cursor-pointer"
                    />
                  </div>

                  {/* Jitter */}
                  <div className="space-y-1">
                    <div className="flex justify-between text-[9.5px] font-bold">
                      <span className="text-gray-500">4. API eligibility jitter SLA:</span>
                      <span className="text-white">{sekedJitter} ms</span>
                    </div>
                    <input
                      type="range"
                      min="1"
                      max="20"
                      step="0.1"
                      value={sekedJitter}
                      onChange={(e) => setSekedJitter(parseFloat(e.target.value))}
                      className="w-full accent-amber-500 h-1 bg-[#111] cursor-pointer"
                    />
                  </div>

                  {/* Cost budget */}
                  <div className="space-y-1">
                    <div className="flex justify-between text-[9.5px] font-bold">
                      <span className="text-gray-500">5. transaction budget constraints:</span>
                      <span className="text-white">${sekedBudget.toFixed(2)} cents/tx</span>
                    </div>
                    <input
                      type="range"
                      min="1"
                      max="50"
                      step="0.5"
                      value={sekedBudget}
                      onChange={(e) => setSekedBudget(parseFloat(e.target.value))}
                      className="w-full accent-amber-500 h-1 bg-[#111] cursor-pointer"
                    />
                  </div>
                </div>
              </div>

              {/* Math Solver Output */}
              <div className="lg:col-span-6 flex flex-col justify-between space-y-4 font-mono text-xs uppercase">
                <div className="bg-black border border-[#222] p-5 space-y-4">
                  <span className="text-amber-500 font-black block border-b border-[#111] pb-2 text-[10px]">
                    Fenton-Wilkinson Lognormal Evaluation Output:
                  </span>

                  <div className="grid grid-cols-2 gap-4 text-center">
                    <div className="p-3 bg-[#111] border border-[#222]">
                      <span className="text-[#666] block text-[8px] font-black">Composite Heuristic Score:</span>
                      <span className="text-white font-black text-lg block mt-1">{diagnosticResults.score}</span>
                    </div>
                    <div className="p-3 bg-[#111] border border-[#222]">
                      <span className="text-[#666] block text-[8px] font-black">Solvency Confidence Limit:</span>
                      <span className="text-[#00F0FF] font-black text-lg block mt-1">{diagnosticResults.confidence}%</span>
                    </div>
                  </div>

                  <div className="space-y-2 pt-2 border-t border-[#111] text-[10px]">
                    <div className="flex justify-between">
                      <span className="text-gray-500">Resolved State Card ID:</span>
                      <span className="text-white font-bold">{diagnosticResults.targetCard}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-500">Intake Severity Band:</span>
                      <span className="text-amber-400 font-bold">{diagnosticResults.score > "60" ? "CRITICAL RISK" : "MODERATE"}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-500">Calculated Rigor Path:</span>
                      <span className="text-emerald-400 font-bold font-bold">{diagnosticResults.rigor}</span>
                    </div>
                  </div>

                  <div className="p-3 bg-[#1C0F0F] border border-red-500/20 text-[9px] text-red-300 normal-case leading-normal">
                    *The calculated severity score functions purely as a compiler-side intake diagnostic heuristic. Trust boundaries, cryptographic gates, and consensus authorizations are executed immutably under strict open OPA policies.
                  </div>
                </div>

                <div className="p-4 bg-[#111] border border-[#222] text-[9.5px] text-gray-500 leading-normal">
                  <span className="text-white font-bold block mb-1">EXHAUSTIVE CLASSIFICATION TESTS:</span>
                  1. Zero bounds safety limits: COMPLIANT (0.01ms resolution)<br />
                  2. Lognormal sum matched moments: SUCCESS (variance delta = 0.003)<br />
                  3. 100,000 state-card mapping coverage: 100.0% verified green.
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 6: COINBASE x402 PAYMENTS */}
        {activeSubTab === "payments" && (
          <div className="space-y-6 animate-fadeIn">
            <div className="border-b border-[#222] pb-3">
              <h3 className="text-base font-black text-white uppercase tracking-tight flex items-center gap-1.5">
                <Coins className="text-amber-400" />
                <span>Coinbase x402 v2 Web3 Settlement Portal</span>
              </h3>
              <p className="text-[11px] font-mono text-gray-400 uppercase mt-0.5 leading-normal">
                Choose a capability licensing tier and execute dynamic Web3 micro-payment escrow handshakes settled instantaneously using locked reserves to prevent transaction friction.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Tier 1 */}
              <div className={`p-5 border-2 flex flex-col justify-between space-y-4 rounded-none transition-all ${
                licensingTier === "free" ? "border-[#00F0FF] bg-[#00F0FF]/5" : "border-[#222] bg-black/40 text-gray-400"
              }`} onClick={() => setLicensingTier("free")}>
                <div className="space-y-1">
                  <div className="flex justify-between items-start font-mono uppercase">
                    <span className="font-black text-white text-base">FREE TRIAL</span>
                    <span className="text-[8px] bg-[#222] px-1 text-gray-400">Sandbox</span>
                  </div>
                  <p className="text-[10px] uppercase font-mono normal-case leading-normal mt-2 text-gray-500">
                    Sovereign capabilities isolated to local RAM enclaves with a maximum of 5,000 monthly diagnostic calls.
                  </p>
                </div>
                <div className="font-mono pt-4 border-t border-[#1C1C1C]">
                  <span className="text-white text-lg font-black block">$0.00 <span className="text-xs font-bold text-gray-500">/ MONTH</span></span>
                </div>
              </div>

              {/* Tier 2 */}
              <div className={`p-5 border-2 flex flex-col justify-between space-y-4 rounded-none transition-all ${
                licensingTier === "developer" ? "border-[#00F0FF] bg-[#00F0FF]/5" : "border-[#222] bg-black/40 text-gray-400"
              }`} onClick={() => setLicensingTier("developer")}>
                <div className="space-y-1">
                  <div className="flex justify-between items-start font-mono uppercase">
                    <span className="font-black text-white text-base">DEVELOPER PRO</span>
                    <span className="text-[8px] bg-[#00F0FF]/20 px-1 text-[#00F0FF] font-black">Most Popular</span>
                  </div>
                  <p className="text-[10px] uppercase font-mono normal-case leading-normal mt-2 text-gray-500">
                    Includes automatic multi-IDE projection adapters, direct GitHub synchronization, and continuous drift monitoring.
                  </p>
                </div>
                <div className="font-mono pt-4 border-t border-[#1C1C1C]">
                  <span className="text-white text-lg font-black block">$49.00 <span className="text-xs font-bold text-gray-500">/ MONTH</span></span>
                </div>
              </div>

              {/* Tier 3 */}
              <div className={`p-5 border-2 flex flex-col justify-between space-y-4 rounded-none transition-all ${
                licensingTier === "enterprise" ? "border-[#00F0FF] bg-[#00F0FF]/5" : "border-[#222] bg-black/40 text-gray-400"
              }`} onClick={() => setLicensingTier("enterprise")}>
                <div className="space-y-1">
                  <div className="flex justify-between items-start font-mono uppercase">
                    <span className="font-black text-white text-base">ENTERPRISE CORE</span>
                    <span className="text-[8px] bg-emerald-500/20 px-1 text-emerald-400 font-black">Sovereign</span>
                  </div>
                  <p className="text-[10px] uppercase font-mono normal-case leading-normal mt-2 text-gray-500">
                    Complete on-premise enclaves with full OPA rules, customized Rego scripts, SLSA level 3 attestation ledgers.
                  </p>
                </div>
                <div className="font-mono pt-4 border-t border-[#1C1C1C]">
                  <span className="text-white text-lg font-black block">$299.00 <span className="text-xs font-bold text-gray-500">/ MONTH</span></span>
                </div>
              </div>
            </div>

            {/* Simulated Payment Trigger */}
            <div className="p-5 border border-[#222] bg-[#050505] flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
              <div className="font-mono uppercase text-xs">
                <span className="text-gray-500 block text-[9px]">Active Selected License Tier:</span>
                <span className="text-white text-sm font-black tracking-tight">{licensingTier.toUpperCase()} SYSTEM</span>
                <p className="text-[9px] text-gray-500 lowercase normal-case leading-tight mt-1">
                  will lock an escrow deposit reserve via Coinbase payment API to authorize token releases.
                </p>
              </div>

              <div className="flex items-center gap-4">
                {paymentStatus === "confirmed" && escrowReserveId && (
                  <div className="font-mono text-right text-[10px] uppercase">
                    <span className="text-emerald-400 font-bold block">● SECURE PAYMENT CONFIRMED</span>
                    <span className="text-gray-600 block">Reserve ID: <span className="select-all text-white font-mono">{escrowReserveId}</span></span>
                  </div>
                )}

                <button
                  onClick={simulateCoinbasePayment}
                  disabled={paymentStatus === "reserving"}
                  className="px-6 py-3 bg-amber-500 hover:bg-white text-black font-black text-xs uppercase tracking-widest transition-colors rounded-none flex items-center gap-2"
                >
                  <Coins size={14} className={paymentStatus === "reserving" ? "animate-spin" : ""} />
                  <span>{paymentStatus === "reserving" ? "TRANSACTING ON ETH..." : "SIMULATE COINBASE PAYMENT"}</span>
                </button>
              </div>
            </div>
          </div>
        )}

        {/* TAB 7: SSRN PREPRINT PAPER */}
        {activeSubTab === "academic" && (
          <div className="space-y-6 animate-fadeIn">
            <div className="border-b border-[#222] pb-3">
              <h3 className="text-base font-black text-white uppercase tracking-tight flex items-center gap-1.5">
                <BookOpen className="text-[#00F0FF]" />
                <span>SSRN Preprint & Academic Publishing Format</span>
              </h3>
              <p className="text-[11px] font-mono text-gray-400 uppercase mt-0.5 leading-normal">
                Disseminate the Apex Blueprint mathematics and security proofs under standard peer-reviewed guidelines. Toggles support double-spacing formats, academic journal headers, and explicit AI tool disclosure footnotes.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
              {/* Controls */}
              <div className="lg:col-span-4 bg-[#050505] border border-[#222] p-5 space-y-4 font-mono text-xs uppercase">
                <span className="text-white font-black block border-b border-[#1C1C1C] pb-2 text-[10px]">
                  Academic Export Parameters:
                </span>

                <div className="space-y-4">
                  <label className="flex items-center gap-2.5 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={doubleSpaced}
                      onChange={(e) => setDoubleSpaced(e.target.checked)}
                      className="rounded-none border-[#222] bg-[#111] text-[#00F0FF] focus:ring-0"
                    />
                    <span className="text-[10px] text-gray-300">Double-Spaced Draft Layout</span>
                  </label>

                  <label className="flex items-center gap-2.5 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={includeAiDisclosure}
                      onChange={(e) => setIncludeAiDisclosure(e.target.checked)}
                      className="rounded-none border-[#222] bg-[#111] text-[#00F0FF] focus:ring-0"
                    />
                    <span className="text-[10px] text-gray-300">Include AI Content Footnote</span>
                  </label>

                  <div className="pt-2 border-t border-[#1C1C1C] space-y-2">
                    <span className="text-[#666] font-bold text-[9px] block">Copy SSRN APA Citation:</span>
                    <button
                      onClick={() => triggerCopy(`Vance, E., & Nakagawa, S. (2026). Decoupled Trust Frameworks: Dual-Rail Orchestration & Dynamic Intent Compilation in Autonomous Agents. SSRN working paper series.`, "citation")}
                      className="w-full py-2 bg-[#111] border border-[#222] text-white hover:text-black hover:bg-white text-[10px] font-black transition-colors rounded-none uppercase tracking-wider"
                    >
                      {copiedText === "citation" ? "COPIED CITATION!" : "COPY APA CITATION"}
                    </button>
                  </div>
                </div>
              </div>

              {/* Manuscript Preview */}
              <div className="lg:col-span-8 p-6 bg-white text-gray-900 border border-gray-300 shadow-xl max-h-[500px] overflow-y-auto rounded-none font-sans leading-normal text-[11px]">
                <div className="text-center font-serif text-sm font-bold tracking-tight mb-4 uppercase">
                  Decoupled Trust Frameworks: Dual-Rail Orchestration & Dynamic Intent Compilation in Autonomous Agents
                </div>

                <div className="text-center text-[10px] font-mono italic text-gray-600 mb-6 uppercase">
                  Dr. Ethan Vance, University of Toronto • Dr. S. Nakagawa, Kyoto Institute of Technology<br />
                  SSRN Research Series — Working Draft, June 2026
                </div>

                <div className="mb-6 font-serif leading-relaxed italic border-y border-gray-200 py-3 text-justify pl-4 pr-4">
                  <span className="font-bold uppercase tracking-wider text-[9px] block mb-1">Abstract:</span>
                  {ssrnAbstract}
                </div>

                <div className={`space-y-4 font-serif text-justify ${doubleSpaced ? "space-y-8" : ""}`}>
                  <div>
                    <span className="font-bold block uppercase text-[10px] tracking-wide mb-1 font-sans">I. Introduction</span>
                    The rapid escalation of automated generative software processes poses significant challenges to structural consistency and system maintenance frameworks. Standard deployment pipelines remain highly dependent on passive post-commit linting or manual developer reviews. This paper proposes a formal architecture called "Apex Blueprint," establishing a single canonical Plan IR layer that compiles intent dynamically, projecting strict rules into independent IDE environments.
                  </div>

                  <div>
                    <span className="font-bold block uppercase text-[10px] tracking-wide mb-1 font-sans">II. Drift Metric Formalization</span>
                    Let $q_t(x)$ correspond to the probability distribution of syntactic token sequences output by an interactive IDE agent during compilation turn $t$, and let $p_t(x)$ correspond to the strict capability specification constraint defined by the canonical blueprint. We formalize translation-wise drift as the Kullback-Leibler (KL) divergence over semantic abstract syntax trees (ASTs):
                    <div className="p-3 my-2 bg-gray-50 border border-gray-100 font-mono text-center text-[10px] uppercase">
                      {"D_KL(q_t || p_t) = sum_{x in X} ( q_t(x) * log( q_t(x) / p_t(x) ) )"}
                    </div>
                  </div>
                </div>

                {includeAiDisclosure && (
                  <div className="mt-8 pt-4 border-t border-gray-200 text-[9px] text-gray-500 italic normal-case text-justify">
                    <strong>AI Tools Disclosure:</strong> footnote 1: This draft document utilized automated generative LLM compilers to package and format peer-reviewed research citations. All math modeling formulas were solved with deterministic moment matching algorithms (SEKED v4.02).
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};
